FROM busybox:latest
RUN echo "First RUN instructions"
RUN echo "Second RUN instructions"
RUN echo "Third RUN instructions"
RUN /bin/bash -c "echo Fourth RUN instructions"

# docker build -t app .
# docker run -it previos_container_id
